In [1]:
from PIL import Image
from skimage import io, transform

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision as tv

outputs = [
    "Dots",
    "Paisley",
    "Qua",
    "Square",
    "Strips",
    "Traingles"
]


# nn model using pytorch schematic
class PatternRecognitionNet(nn.Module):

    def __init__(self):
        super(PatternRecognitionNet, self).__init__()

        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 73 * 73, 120) 
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 6)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
def getImageTensor(path):
    
    # loading image from local memory
    
    image = io.imread(path)
    
    return image
    

# transforms image to grayscale tensor
def myTransform(image):

    transformedImage =  tv.transforms.Compose([
                        tv.transforms.ToPILImage(),
                        tv.transforms.Grayscale(num_output_channels=1),
                        tv.transforms.ToTensor()
                      ])(image)
    
    transformedImage = transformedImage[0]

    return transformedImage

# create parrter recognition model 

PATH = "/home/krys/POLIBUDA/Patterns_database/modelV3.pt"

pattNet = PatternRecognitionNet()
pattNet.load_state_dict(torch.load(PATH))
pattNet.eval()

PatternRecognitionNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=85264, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=6, bias=True)
)

In [2]:
import os

path = "/home/krys/POLIBUDA/Patterns_database/test_image/"
test_images = os.listdir(path)

Preds = 0
Unpreds = 0
Ex = 0

for k in range(len(test_images)):
    try:
        print("===================================================================\n")

        print(path + test_images[k] + "\n")

        image = getImageTensor(path + test_images[k])
        t_image = myTransform(image)
        input = t_image.view(-1,1,300,300)
        output = pattNet(input)
        print(output)
        val, idx = output[0].max(0)
        
        if val > 0.6: 
            print("\n")
            print("Your predicted output is:", outputs[idx])
            print("\n===================================================================\n")
            Preds += 1
        else:
            print("Im not sure")
            Unpreds += 1
    except: 
        print("Exeption\n")
        Ex += 1
        pass
    
print("Preds: ",Preds , "\nUnpreds: ", Unpreds, "\nExeptions: ", Ex)


/home/krys/POLIBUDA/Patterns_database/test_image/pas54o.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas55j.jpg

Exeption


/home/krys/POLIBUDA/Patterns_database/test_image/qua55e.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr54h.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq56f.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq55a.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq56a.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.19

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr55n.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua55w.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq54d.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr54v.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas55a.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas54d.jpg

tensor([[0.12

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr56o.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr55a.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas55o.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua55k.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas55c.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr55v.jpg

tensor([[0.12

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua56i.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua55i.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua56p.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas56r.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas54t.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq54v.jpg

tensor([[0.

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr56g.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr55.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq54.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq54k.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/pas56e.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq54e.jpg

tensor([[0.1260, 

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/tr54f.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua55s.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua54n.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq55j.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/qua54c.jpg

tensor([[0.1260, 0.1400, 0.1556, 0.1729, 0.1921, 0.2134]],
       grad_fn=<AddmmBackward>)
Im not sure

/home/krys/POLIBUDA/Patterns_database/test_image/sq55i.jpg

tensor([[0.12